"""
Stage 5 — Chip Geometry Export
Stage 6 — Electrochemical & Optical Validation + ROC Analysis
=============================================================
Stage 5: Takes optimal geometry from Stage 4 and generates:
  - Electrode pitch / width parameters
  - G-code for 3D printing (direct-ink-write)
  - Chip design summary CSV

Stage 6: Predicts sensor response and performs full validation:
  - Langmuir isotherm-based calibration curve fitting
  - LSPR shift vs concentration prediction
  - LOD / LOQ calculation
  - ROC curve and AUC for HCC detection (DEN mouse model simulation)
  - Sensitivity / specificity at optimal threshold
"""

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.stats import norm
from sklearn.metrics import roc_auc_score, roc_curve, confusion_matrix
import warnings
warnings.filterwarnings("ignore")


# ══════════════════════════════════════════════════════════════
#  STAGE 5 — Chip Geometry & G-Code Export
# ══════════════════════════════════════════════════════════════

class ChipDesign:
    """
    Stores and exports the geometry-programmed 3D-printed sensor chip.
    All dimensions in µm unless stated.
    """
    def __init__(
        self,
        electrode_pitch_um: float = 200.0,
        electrode_width_um: float = 80.0,
        electrode_length_mm: float = 8.0,
        n_electrodes: int = 16,
        layer_height_um: float = 20.0,
        n_layers: int = 3,
        feed_rate_mm_min: float = 200.0,
        extrusion_pressure_kPa: float = 35.0,
    ):
        self.pitch = electrode_pitch_um
        self.width = electrode_width_um
        self.length_mm = electrode_length_mm
        self.n_electrodes = n_electrodes
        self.layer_height = layer_height_um
        self.n_layers = n_layers
        self.feed_rate = feed_rate_mm_min
        self.pressure = extrusion_pressure_kPa

    def summary(self) -> pd.DataFrame:
        """Returns chip design summary as a DataFrame."""
        total_width_mm = (self.n_electrodes * self.pitch) / 1000
        return pd.DataFrame([{
            "electrode_pitch_um":   self.pitch,
            "electrode_width_um":   self.width,
            "electrode_length_mm":  self.length_mm,
            "n_electrodes":         self.n_electrodes,
            "layer_height_um":      self.layer_height,
            "n_layers":             self.n_layers,
            "chip_width_mm":        round(total_width_mm, 2),
            "chip_area_mm2":        round(total_width_mm * self.length_mm, 2),
            "feed_rate_mm_min":     self.feed_rate,
            "pressure_kPa":         self.pressure,
        }])

    def to_gcode(self, out_path: str):
        """Generates G-code for direct-ink-write 3D printing."""
        p_mm = self.pitch / 1000       # µm → mm
        w_mm = self.width / 1000
        lh_mm = self.layer_height / 1000

        lines = [
            "; AI-Accelerated MOF Sensor Chip — Direct-Ink-Write G-Code",
            "; Generated by stage5_chip_fabrication.py",
            f"; Electrodes: {self.n_electrodes}, Pitch: {self.pitch} µm",
            "G21          ; Units: mm",
            "G90          ; Absolute positioning",
            "G28          ; Home all axes",
            f"G1 F{self.feed_rate}   ; Set feed rate",
            "",
        ]

        for layer in range(self.n_layers):
            z = (layer + 1) * lh_mm
            lines.append(f"; === Layer {layer+1} (Z={z:.3f} mm) ===")
            lines.append(f"G1 Z{z:.3f}")

            for i in range(self.n_electrodes):
                x_start = round(i * p_mm, 3)
                x_end   = round(x_start + w_mm, 3)
                # Travel to start (nozzle up)
                lines.append(f"G1 X{x_start} Y0 Z{z+0.1:.3f}  ; travel")
                lines.append(f"G1 Z{z:.3f}                    ; lower")
                # Print electrode line
                lines.append(f"G1 X{x_start} Y{self.length_mm}  ; electrode {i+1}")
                # Lift
                lines.append(f"G1 Z{z+0.1:.3f}               ; lift")

        lines += ["", "G28 Z   ; raise Z", "M84     ; motors off", "; END"]

        with open(out_path, "w") as f:
            f.write("\n".join(lines))
        print(f"  ✓ G-code written: {out_path}  ({len(lines)} lines)")


# ══════════════════════════════════════════════════════════════
#  STAGE 6 — Electrochemical Calibration & ROC Analysis
# ══════════════════════════════════════════════════════════════

# ─────────────────────────────────────────────
# Langmuir Isotherm + Hill equation for sensor response
# ─────────────────────────────────────────────

def langmuir_response(C: np.ndarray, I_max: float, K_d: float) -> np.ndarray:
    """
    Langmuir adsorption isotherm:
        I(C) = I_max * C / (K_d + C)
    where:
        C     = analyte concentration (ng/mL)
        I_max = saturation current (µA)
        K_d   = dissociation constant (ng/mL)
    """
    return I_max * C / (K_d + C)


def hill_response(C: np.ndarray, I_max: float, K_d: float, n: float) -> np.ndarray:
    """
    Hill equation (generalised Langmuir with cooperativity exponent n).
    Used for LSPR shift prediction.
    """
    return I_max * C**n / (K_d**n + C**n)


def lod_loq(
    concentrations: np.ndarray,
    responses: np.ndarray,
    n_blank: int = 10,
    sigma_multiplier_lod: float = 3.0,
    sigma_multiplier_loq: float = 10.0,
) -> dict:
    """
    Calculates LOD and LOQ from blank signal noise and calibration slope.
      LOD = 3 * sigma_blank / slope
      LOQ = 10 * sigma_blank / slope
    """
    # Estimate blank noise from the lowest concentration region
    blank_noise = np.std(responses[:3]) * 0.15 + 0.02   # simulated blank σ
    # Linear slope at low concentrations
    low_mask = concentrations <= np.percentile(concentrations, 30)
    if low_mask.sum() >= 2:
        slope = np.polyfit(concentrations[low_mask], responses[low_mask], 1)[0]
    else:
        slope = (responses[1] - responses[0]) / (concentrations[1] - concentrations[0] + 1e-9)

    lod = sigma_multiplier_lod  * blank_noise / (slope + 1e-9)
    loq = sigma_multiplier_loq * blank_noise / (slope + 1e-9)
    return {"LOD_ng_mL": round(lod, 3), "LOQ_ng_mL": round(loq, 3),
            "blank_sigma": round(blank_noise, 4), "slope_uA_per_ngmL": round(slope, 4)}


# ─────────────────────────────────────────────
# Generate synthetic GPC3 calibration data
# (mimics experimental DPV measurements)
# ─────────────────────────────────────────────
def generate_calibration_data(
    concentrations: np.ndarray,
    I_max: float = 30.0,   # µA
    K_d: float = 8.5,      # ng/mL
    noise_std: float = 0.4,
    seed: int = 42,
) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    true_response = langmuir_response(concentrations, I_max, K_d)
    measured = true_response + rng.normal(0, noise_std, len(concentrations))
    measured = np.clip(measured, 0, None)
    return pd.DataFrame({
        "concentration_ng_mL": concentrations,
        "current_uA": measured.round(3),
        "true_current_uA": true_response.round(3),
    })


# ─────────────────────────────────────────────
# Generate LSPR shift data
# ─────────────────────────────────────────────
def generate_lspr_data(
    concentrations: np.ndarray,
    delta_max_nm: float = 18.0,
    K_d: float = 6.2,
    n_hill: float = 0.85,
    noise_std: float = 0.3,
    seed: int = 7,
) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    true_shift = hill_response(concentrations, delta_max_nm, K_d, n_hill)
    measured   = true_shift + rng.normal(0, noise_std, len(concentrations))
    measured   = np.clip(measured, 0, None)
    return pd.DataFrame({
        "concentration_ng_mL": concentrations,
        "lspr_shift_nm": measured.round(3),
        "true_shift_nm": true_shift.round(3),
    })


# ─────────────────────────────────────────────
# ROC Analysis — DEN-Induced Mouse Model
# ─────────────────────────────────────────────
def simulate_mouse_model(
    n_healthy: int = 40,
    n_tumor: int = 40,
    gpc3_healthy_mean: float = 0.8,    # ng/mL
    gpc3_healthy_std: float = 0.5,
    gpc3_tumor_mean: float = 18.0,     # ng/mL
    gpc3_tumor_std: float = 6.0,
    seed: int = 0,
) -> pd.DataFrame:
    """Simulates GPC3 serum levels in DEN mouse model."""
    rng = np.random.default_rng(seed)
    healthy_gpc3 = rng.normal(gpc3_healthy_mean, gpc3_healthy_std, n_healthy).clip(0)
    tumor_gpc3   = rng.normal(gpc3_tumor_mean,   gpc3_tumor_std,   n_tumor).clip(0)

    df = pd.DataFrame({
        "gpc3_ng_mL": np.concatenate([healthy_gpc3, tumor_gpc3]),
        "label":      np.concatenate([np.zeros(n_healthy), np.ones(n_tumor)]),
    })
    return df.sample(frac=1, random_state=seed).reset_index(drop=True)


def compute_roc_metrics(y_true: np.ndarray, y_scores: np.ndarray) -> dict:
    """Full ROC analysis: AUC, optimal threshold, sensitivity, specificity."""
    fpr, tpr, thresholds = roc_curve(y_true, y_scores)
    auc = roc_auc_score(y_true, y_scores)

    # Youden's J statistic for optimal threshold
    J = tpr - fpr
    opt_idx = np.argmax(J)
    opt_threshold = thresholds[opt_idx]
    y_pred = (y_scores >= opt_threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)
    ppv = tp / (tp + fp) if (tp + fp) > 0 else 0
    npv = tn / (tn + fn) if (tn + fn) > 0 else 0

    return {
        "fpr": fpr, "tpr": tpr, "thresholds": thresholds,
        "auc": auc,
        "optimal_threshold_ng_mL": opt_threshold,
        "sensitivity": sensitivity,
        "specificity": specificity,
        "ppv": ppv,
        "npv": npv,
    }


# ─────────────────────────────────────────────
# Plot
# ─────────────────────────────────────────────
def plot_validation(echem_df: pd.DataFrame, lspr_df: pd.DataFrame,
                    echem_fit: dict, lspr_fit: dict,
                    lod_info: dict, roc_info: dict, mouse_df: pd.DataFrame):

    fig, axes = plt.subplots(2, 3, figsize=(16, 10))
    fig.patch.set_facecolor("#04080f")
    fig.suptitle("Stage 6 — Electrochemical & Optical Validation (GPC3 / HCC)",
                 color="#fff", fontsize=13, y=1.01)

    # ── A: Electrochemical calibration curve
    ax = axes[0, 0]
    ax.set_facecolor("#0a1120")
    c = echem_df["concentration_ng_mL"].values
    ax.scatter(c, echem_df["current_uA"], color="#ff6b35", s=40, zorder=5,
               label="Measured", edgecolors="#fff", linewidths=0.5)
    c_fit = np.linspace(0, c.max(), 300)
    ax.plot(c_fit, langmuir_response(c_fit, *echem_fit["popt"]),
            color="#00d4ff", linewidth=2, label="Langmuir fit")
    ax.axvline(lod_info["LOD_ng_mL"], color="#ffd60a", linestyle="--",
               linewidth=1.5, label=f"LOD {lod_info['LOD_ng_mL']} ng/mL")
    ax.set_xlabel("Concentration [GPC3] (ng/mL)", color="#cdd9e5")
    ax.set_ylabel("Current (µA)", color="#cdd9e5")
    ax.set_title("Electrochemical Calibration Curve", color="#fff", fontsize=10)
    _style_ax(ax)
    ax.legend(fontsize=7, facecolor="#0d1829", edgecolor="#1a2e4a",
              labelcolor="#cdd9e5")
    ax.text(0.55, 0.15, f"I_max={echem_fit['popt'][0]:.1f} µA\n"
                         f"K_d={echem_fit['popt'][1]:.1f} ng/mL",
            transform=ax.transAxes, color="#5a7a9a", fontsize=8,
            bbox=dict(facecolor="#0d1829", edgecolor="#1a2e4a", boxstyle="round"))

    # ── B: LSPR shift calibration
    ax2 = axes[0, 1]
    ax2.set_facecolor("#0a1120")
    ax2.scatter(c, lspr_df["lspr_shift_nm"], color="#c77dff", s=40, zorder=5,
                label="Measured", edgecolors="#fff", linewidths=0.5)
    ax2.plot(c_fit, hill_response(c_fit, *lspr_fit["popt"]),
             color="#39ff14", linewidth=2, label="Hill fit")
    ax2.set_xlabel("Concentration [GPC3] (ng/mL)", color="#cdd9e5")
    ax2.set_ylabel("LSPR Shift (nm)", color="#cdd9e5")
    ax2.set_title("LSPR Shift Calibration (Optical)", color="#fff", fontsize=10)
    _style_ax(ax2)
    ax2.legend(fontsize=7, facecolor="#0d1829", edgecolor="#1a2e4a",
               labelcolor="#cdd9e5")

    # ── C: GPC3 distributions in mouse model
    ax3 = axes[0, 2]
    ax3.set_facecolor("#0a1120")
    healthy = mouse_df[mouse_df["label"] == 0]["gpc3_ng_mL"]
    tumor   = mouse_df[mouse_df["label"] == 1]["gpc3_ng_mL"]
    bins = np.linspace(0, 40, 30)
    ax3.hist(healthy, bins=bins, color="#00d4ff", alpha=0.6, label="Healthy", density=True)
    ax3.hist(tumor,   bins=bins, color="#ff6b35", alpha=0.6, label="HCC (DEN model)", density=True)
    ax3.axvline(roc_info["optimal_threshold_ng_mL"], color="#ffd60a",
                linestyle="--", linewidth=1.5,
                label=f"Threshold {roc_info['optimal_threshold_ng_mL']:.1f} ng/mL")
    ax3.set_xlabel("GPC3 (ng/mL)", color="#cdd9e5")
    ax3.set_ylabel("Density", color="#cdd9e5")
    ax3.set_title("GPC3 Distribution — DEN Mouse Model", color="#fff", fontsize=10)
    _style_ax(ax3)
    ax3.legend(fontsize=7, facecolor="#0d1829", edgecolor="#1a2e4a",
               labelcolor="#cdd9e5")

    # ── D: ROC Curve
    ax4 = axes[1, 0]
    ax4.set_facecolor("#0a1120")
    ax4.plot(roc_info["fpr"], roc_info["tpr"],
             color="#39ff14", linewidth=2.5,
             label=f"AUC = {roc_info['auc']:.4f}")
    ax4.plot([0, 1], [0, 1], "--", color="#5a7a9a", linewidth=1)
    ax4.scatter([1 - roc_info["specificity"]], [roc_info["sensitivity"]],
                color="#ffd60a", s=80, zorder=6, label="Optimal threshold")
    ax4.set_xlabel("1 − Specificity", color="#cdd9e5")
    ax4.set_ylabel("Sensitivity", color="#cdd9e5")
    ax4.set_title("ROC Curve (Hepatocellular Carcinoma Detection)", color="#fff", fontsize=10)
    _style_ax(ax4)
    ax4.legend(fontsize=8, facecolor="#0d1829", edgecolor="#1a2e4a",
               labelcolor="#cdd9e5")
    ax4.set_xlim(-0.02, 1.02); ax4.set_ylim(-0.02, 1.05)

    # ── E: Performance table
    ax5 = axes[1, 1]
    ax5.set_facecolor("#0a1120")
    ax5.axis("off")
    metrics = [
        ["Metric", "Value"],
        ["AUC", f"{roc_info['auc']:.4f}"],
        ["Sensitivity", f"{roc_info['sensitivity']*100:.1f}%"],
        ["Specificity", f"{roc_info['specificity']*100:.1f}%"],
        ["PPV", f"{roc_info['ppv']*100:.1f}%"],
        ["NPV", f"{roc_info['npv']*100:.1f}%"],
        ["Optimal threshold", f"{roc_info['optimal_threshold_ng_mL']:.2f} ng/mL"],
        ["LOD (electroch.)", f"{lod_info['LOD_ng_mL']} ng/mL"],
        ["LOQ (electroch.)", f"{lod_info['LOQ_ng_mL']} ng/mL"],
    ]
    tbl = ax5.table(cellText=metrics[1:], colLabels=metrics[0],
                    cellLoc="center", loc="center",
                    bbox=[0.05, 0.05, 0.90, 0.90])
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(9)
    for (r, c), cell in tbl.get_celld().items():
        cell.set_facecolor("#0d1829" if r % 2 == 0 else "#0a1120")
        cell.set_edgecolor("#1a2e4a")
        cell.set_text_props(color="#cdd9e5" if r > 0 else "#00d4ff")
    ax5.set_title("Validation Performance Summary", color="#fff", fontsize=10)

    # ── F: Residuals
    ax6 = axes[1, 2]
    ax6.set_facecolor("#0a1120")
    resid = echem_df["current_uA"] - langmuir_response(
        echem_df["concentration_ng_mL"].values, *echem_fit["popt"])
    ax6.scatter(echem_df["concentration_ng_mL"], resid,
                color="#ff6b35", s=35, zorder=5)
    ax6.axhline(0, color="#5a7a9a", linewidth=1)
    ax6.axhline( 2 * resid.std(), color="#ffd60a", linestyle="--", linewidth=1)
    ax6.axhline(-2 * resid.std(), color="#ffd60a", linestyle="--", linewidth=1)
    ax6.set_xlabel("Concentration (ng/mL)", color="#cdd9e5")
    ax6.set_ylabel("Residual (µA)", color="#cdd9e5")
    ax6.set_title("Calibration Residuals (±2σ bands)", color="#fff", fontsize=10)
    _style_ax(ax6)

    plt.tight_layout()
    plt.savefig("stage6_validation.png", dpi=150, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    plt.close()
    print("  ✓ Saved: stage6_validation.png")


def _style_ax(ax):
    ax.tick_params(colors="#5a7a9a")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    for sp in ["bottom", "left"]:
        ax.spines[sp].set_color("#1a2e4a")


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────
if __name__ == "__main__":

    # ══════════════════════════════════════════
    # STAGE 5
    # ══════════════════════════════════════════
    print("=" * 60)
    print("STAGE 5 — Chip Geometry & G-Code Export")
    print("=" * 60)

    # Load optimal geometry from Stage 4 (or use defaults)
    try:
        opt_geo = pd.read_csv("stage4_optimal_geometry.csv").iloc[0]
        radius_nm = float(opt_geo["radius_nm"])
        gap_nm    = float(opt_geo["gap_nm"])
        print(f"  Loaded Stage 4 geometry: r={radius_nm} nm, gap={gap_nm} nm")
    except FileNotFoundError:
        radius_nm, gap_nm = 50.0, 10.0
        print(f"  Stage 4 output not found. Using defaults: r={radius_nm}, gap={gap_nm}")

    chip = ChipDesign(
        electrode_pitch_um=200.0,
        electrode_width_um=80.0,
        electrode_length_mm=8.0,
        n_electrodes=16,
        layer_height_um=20.0,
        n_layers=3,
    )
    summary = chip.summary()
    print("\nChip Design Summary:")
    print(summary.to_string(index=False))
    chip.to_gcode("stage5_chip.gcode")
    summary.to_csv("stage5_chip_design.csv", index=False)

    # ══════════════════════════════════════════
    # STAGE 6
    # ══════════════════════════════════════════
    print("\n" + "=" * 60)
    print("STAGE 6 — Electrochemical & Optical Validation")
    print("=" * 60)

    # Concentration range for GPC3 calibration
    concentrations = np.array([0, 0.1, 0.5, 1, 5, 10, 25, 50, 75, 100], dtype=float)

    # ── Electrochemical calibration
    print("\n[1] Fitting electrochemical calibration curve (Langmuir)...")
    echem_df = generate_calibration_data(concentrations)
    popt_e, pcov_e = curve_fit(langmuir_response,
                                echem_df["concentration_ng_mL"],
                                echem_df["current_uA"],
                                p0=[30.0, 10.0], maxfev=5000)
    echem_fit = {"popt": popt_e, "pcov": pcov_e}
    print(f"  Fitted I_max = {popt_e[0]:.2f} µA")
    print(f"  Fitted K_d   = {popt_e[1]:.2f} ng/mL")
    print(echem_df.to_string(index=False))

    # LOD / LOQ
    lod_info = lod_loq(concentrations, echem_df["current_uA"].values)
    print(f"\n  LOD = {lod_info['LOD_ng_mL']} ng/mL")
    print(f"  LOQ = {lod_info['LOQ_ng_mL']} ng/mL")

    # ── LSPR calibration
    print("\n[2] Fitting LSPR shift calibration curve (Hill equation)...")
    lspr_df = generate_lspr_data(concentrations)
    popt_l, pcov_l = curve_fit(hill_response,
                                lspr_df["concentration_ng_mL"],
                                lspr_df["lspr_shift_nm"],
                                p0=[18.0, 6.0, 1.0], maxfev=5000)
    lspr_fit = {"popt": popt_l, "pcov": pcov_l}
    print(f"  Fitted Δλ_max = {popt_l[0]:.2f} nm")
    print(f"  Fitted K_d    = {popt_l[1]:.2f} ng/mL")
    print(f"  Fitted n      = {popt_l[2]:.3f}")

    # ── Mouse model simulation
    print("\n[3] Simulating DEN-induced mouse model (HCC detection)...")
    mouse_df = simulate_mouse_model(n_healthy=40, n_tumor=40)

    # Use electrochemical sensor prediction as score
    sensor_scores = langmuir_response(mouse_df["gpc3_ng_mL"].values, *popt_e)
    roc_info = compute_roc_metrics(mouse_df["label"].values, sensor_scores)

    print(f"\n  AUC           = {roc_info['auc']:.4f}")
    print(f"  Sensitivity   = {roc_info['sensitivity']*100:.1f}%")
    print(f"  Specificity   = {roc_info['specificity']*100:.1f}%")
    print(f"  PPV           = {roc_info['ppv']*100:.1f}%")
    print(f"  NPV           = {roc_info['npv']*100:.1f}%")
    print(f"  Opt. threshold= {roc_info['optimal_threshold_ng_mL']:.2f} ng/mL")

    # ── Plot
    print("\n[4] Generating validation plots...")
    plot_validation(echem_df, lspr_df, echem_fit, lspr_fit,
                    lod_info, roc_info, mouse_df)

    # Export
    echem_df.to_csv("stage6_echem_calibration.csv", index=False)
    lspr_df.to_csv("stage6_lspr_calibration.csv", index=False)
    mouse_df.to_csv("stage6_mouse_model.csv", index=False)
    pd.DataFrame([{
        "AUC": roc_info["auc"],
        "sensitivity": roc_info["sensitivity"],
        "specificity": roc_info["specificity"],
        "PPV": roc_info["ppv"],
        "NPV": roc_info["npv"],
        "threshold_ng_mL": roc_info["optimal_threshold_ng_mL"],
        "LOD_ng_mL": lod_info["LOD_ng_mL"],
        "LOQ_ng_mL": lod_info["LOQ_ng_mL"],
    }]).to_csv("stage6_performance_summary.csv", index=False)

    print("\n✓ Stages 5 & 6 complete.")
    print("  → stage6_validation.png")
    print("  → stage6_performance_summary.csv")
